<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FairvilleInn.Infrastructure</RootNamespace>
    <AssemblyName>FairvilleInn.Infrastructure</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\FairvilleInn.Application.csproj" />
  </ItemGroup>
</Project>
